package main.java.phsimulation.config;

public final class SimulationPreset {
    private SimulationPreset(){}

    public static SimulationConfig getPresetForSize(WorldSize size) {
        return switch (size){
            case SMALL -> new SimulationConfig.Builder()
                    .worldMap()
                        .height(10)
                        .width(10)
                        .done()
                    .predator()
                        .speed(2)
                        .maxHp(100)
                        .attackPower(25)
                        .done()
                    .herbivore()
                        .speed(1)
                        .maxHp(60)
                        .hpRestoredPerGrass(20)
                        .done()
                    .entitiesCount()
                        .predatorCount(50)
                        .herbivoreCount(15)
                        .grassCount(50)
                        .treeCount(20)
                        .rockCount(10)
                        .done()
                    .minThresholds()
                        .grassMinThreshold(0.3)
                        .herbivoreMinThreshold(0.3)
                        .done()
                    .build();

            case MEDIUM -> new SimulationConfig.Builder()
                    .worldMap()
                        .height(25)
                        .width(30)
                        .done()
                    .predator()
                        .speed(2)
                        .maxHp(10)
                        .attackPower(50)
                        .done()
                    .herbivore()
                        .speed(0)
                        .maxHp(60)
                        .hpRestoredPerGrass(10)
                        .done()
                    .entitiesCount()
                        .predatorCount(50)
                        .herbivoreCount(15)
                        .grassCount(50)
                        .treeCount(20)
                        .rockCount(10)
                        .done()
                    .minThresholds()
                        .grassMinThreshold(0.3)
                        .herbivoreMinThreshold(0.2)
                        .done()
                    .build();

            case LARGE -> new SimulationConfig.Builder()
                    .worldMap()
                        .height(20)
                        .width(30)
                        .done()
                    .predator()
                        .speed(2)
                        .maxHp(10)
                        .attackPower(50)
                        .done()
                    .herbivore()
                        .speed(0)
                        .maxHp(60)
                        .hpRestoredPerGrass(10)
                        .done()
                    .entitiesCount()
                        .predatorCount(50)
                        .herbivoreCount(15)
                        .grassCount(50)
                        .treeCount(20)
                        .rockCount(10)
                        .done()
                    .minThresholds()
                        .grassMinThreshold(0.3)
                        .herbivoreMinThreshold(0.5)
                        .done()
                    .build();
        };
    }
}
